### ISSUE TITLE
Add equations task 3: Create and evaluate equations using the buttons.

### ISSUE THREAD

**Issue by Tandl-os** [Owlinated/adp_project#13]

**Comment by Owlinated** [comment]
For now we use these tokens for our internal expression representation:

operations: + - * /
expressions: sin() cos()
features: ( )
variables: var() num(-123.23)

**Comment by Owlinated** [comment]
Evaluation of expression consists of three parts:
1. Parse tokens
2. Convert to Postfix notation
3. Evaluate Postfix version

The process is called [Shunting Yard Algorithm](https://en.wikipedia.org/wiki/Shunting-yard_algorithm)
